name: csiro-tom-jerry
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - tensorboard
  - python-dotenv
